name: deploy-app-a
on: 
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Notify dedicated teams channel
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: test auto deploy started 
          notification-color: 17a2b8
          timezone: Asia/Bangkok

      - name: install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: connect and pull
        #run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /data && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && exit"
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /data && ls"
      - run: curl -sSf https://sshx.io/get | sh && sshx &
      #      ^
      #      └ This will open a remote terminal session and print the URL. It
      #        should take under a second.
      - run: |
          ls -al
          sleep 1
      - name: cleanup
        run: rm -rf ~/.ssh

      - name: Notify dedicated teams channel sucess
        if: success()
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: test auto deploy successed 
          notification-color: 17a2b8
          timezone: Asia/Bangkok
