name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ... other steps ...

      - run: curl -sSf https://sshx.io/get | sh && sshx &
      - run: sleep 120s
      #      ^
      #      └ This will open a remote terminal session and print the URL. It
      #        should take under a second.
